In [1]:
import torch

In [2]:
q = torch.FloatTensor(4, 10, 7)

In [3]:
q

tensor([[[ 0.0000e+00,  0.0000e+00,  9.8091e-45,  0.0000e+00, -2.7286e+05,
           4.5754e-41, -3.3159e+08],
         [ 4.5754e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
                  nan,         nan],
         [ 0.0000e+00,  0.0000e+00,  1.4013e-45,  4.5754e-41,  0.0000e+00,
           0.0000e+00,  1.5414e-44],
         [ 0.0000e+00, -1.2586e+09,  4.5754e-41, -3.3159e+08,  4.5754e-41,
                  nan,         nan],
         [ 0.0000e+00,  0.0000e+00,         nan,         nan, -1.8447e+10,
           4.5754e-41,  1.4013e-45],
         [ 4.5754e-41,  1.0089e-43,  0.0000e+00,  9.8091e-45,  0.0000e+00,
          -1.8400e+10,  4.5754e-41],
         [-1.4457e+04,  4.5754e-41,  0.0000e+00,  0.0000e+00,  1.4013e-45,
           0.0000e+00,  1.4013e-45],
         [ 0.0000e+00, -1.8447e+10,  4.5754e-41,  1.4013e-45,  4.5754e-41,
           2.0179e-43,  0.0000e+00],
         [ 4.2039e-45,  0.0000e+00, -1.8400e+10,  4.5754e-41, -1.4457e+04,
           4.5754e-41,  0.000

In [4]:
initial_state = (0. 3)

SyntaxError: invalid syntax (<ipython-input-4-62efd3a0aaf5>, line 1)

In [5]:
initial_state = (0, 3)

In [6]:
q[0]

tensor([[ 0.0000e+00,  0.0000e+00,  9.8091e-45,  0.0000e+00, -2.7286e+05,
          4.5754e-41, -3.3159e+08],
        [ 4.5754e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
                 nan,         nan],
        [ 0.0000e+00,  0.0000e+00,  1.4013e-45,  4.5754e-41,  0.0000e+00,
          0.0000e+00,  1.5414e-44],
        [ 0.0000e+00, -1.2586e+09,  4.5754e-41, -3.3159e+08,  4.5754e-41,
                 nan,         nan],
        [ 0.0000e+00,  0.0000e+00,         nan,         nan, -1.8447e+10,
          4.5754e-41,  1.4013e-45],
        [ 4.5754e-41,  1.0089e-43,  0.0000e+00,  9.8091e-45,  0.0000e+00,
         -1.8400e+10,  4.5754e-41],
        [-1.4457e+04,  4.5754e-41,  0.0000e+00,  0.0000e+00,  1.4013e-45,
          0.0000e+00,  1.4013e-45],
        [ 0.0000e+00, -1.8447e+10,  4.5754e-41,  1.4013e-45,  4.5754e-41,
          2.0179e-43,  0.0000e+00],
        [ 4.2039e-45,  0.0000e+00, -1.8400e+10,  4.5754e-41, -1.4457e+04,
          4.5754e-41,  0.0000e+00],
        [ 

In [7]:
q[0][0]

tensor([ 0.0000e+00,  0.0000e+00,  9.8091e-45,  0.0000e+00, -2.7286e+05,
         4.5754e-41, -3.3159e+08])

In [8]:
goal = (7, 3)

In [9]:
abs

<function abs(x, /)>

In [10]:
abs(-1)

1

In [11]:
def distance(x, y):
    return abs(x - goal[0]) + abs(y - abs[1])

In [12]:
distance(0, 0)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [13]:
def distance(x, y):
    return abs(x - goal[0]) + abs(y - goal[1])

In [14]:
distance(0, 0)

10

In [15]:
distance(7, 3)

0

In [16]:
q[0][0][0] = 1

In [17]:
q[0][0]

tensor([ 1.0000e+00,  0.0000e+00,  9.8091e-45,  0.0000e+00, -2.7286e+05,
         4.5754e-41, -3.3159e+08])

In [18]:
for i in range(4):
    for j in range(10):
        for k in range(7):
            q[i][j][k] = (-1) * distance(j, k)

In [19]:
q[0][0]

tensor([-10.,  -9.,  -8.,  -7.,  -8.,  -9., -10.])

In [20]:
n_epochs = 0

In [21]:
epsilon = 0.1

In [22]:
epsilon = 0.2

In [23]:
import random

In [24]:
def epsilon_greedy(state):
    if random.uniform(0, 1) < epsilon:
        return random.choice([0, 1, 2, 3])
    max_val = -1000
    max_args = []
    for i in range(4):
        if q[i][state[0]][state[1]] > max_val:
            max_args.append(i)
            max_val = q[i][state[0]][state[1]]
    return random.choice(max_args)



In [25]:
epsilon_greedy([0, 0])

3

In [26]:
epsilon_greedy([0, 0])

0

In [27]:
epsilon_greedy([0, 0])

0

In [28]:
epsilon_greedy([0, 0])


0

In [29]:
  epsilon_greedy([0, 0])

0

In [30]:
epsilon_greedy([0, 0])




3

In [31]:
epsilon_greedy([0, 0])

0

In [32]:
epsilon_greedy([0, 0])

0

In [33]:
epsilon_greedy([0, 0])

0

In [34]:
epsilon_greedy([0, 0])

0

In [35]:
epsilon_greedy([0, 0])

0

In [36]:
epsilon_greedy([0, 0])


0

In [37]:
epsilon_greedy([0, 0])

3

In [38]:
epsilon_greedy([0, 0])

2

In [39]:
epsilon_greedy([0, 0])

3

In [40]:
epsilon_greedy([0, 0])

0

In [41]:
epsilon_greedy([0, 0])

2

In [42]:
epsilon_greedy([0, 0])

0

In [43]:
epsilon_greedy([1, 3])

0

In [44]:
epsilon_greedy([1, 3])

0

In [45]:
epsilon_greedy([1, 3])

0

In [46]:
epsilon_greedy([1, 3])

0

In [47]:
epsilon_greedy([1, 3])

0

In [48]:
epsilon_greedy([1, 3])

0

In [49]:
epsilon_greedy([1, 3])


0

In [50]:
def epsilon_greedy(state):
    if random.uniform(0, 1) < epsilon:
        return random.choice([0, 1, 2, 3])
    max_val = -1000
    max_args = []
    for i in range(4):
        if q[i][state[0]][state[1]] > max_val:
            max_args = [i]
            max_val = q[i][state[0]][state[1]]
        elif q[i][state[0]][state[1]] == max_val:
            max_args.append(i)
    return random.choice(max_args)

In [51]:
epsilon_greedy([1, 3])

0

In [52]:
epsilon_greedy([1, 3])

1

In [53]:
epsilon_greedy([1, 3])

3

In [54]:
epsilon_greedy([1, 3])

2

In [55]:
epsilon_greedy([1, 3])

1

In [56]:
epsilon_greedy([1, 3])

0

In [57]:
epsilon_greedy([1, 3])



2

In [58]:
epsilon_greedy([1, 3])

0

In [59]:
epsilon_greedy([1, 3])

3

In [60]:
epsilon_greedy([1, 3])

3

In [ ]:
def step(state):
    action = epsilon_greedy(state)
    